const { Client } = require("pg");

const client = new Client({
    host: "localhost",
    user: "postgres",
    database: "inventory_db",
    password: "@Salman123",
    port: 5432,
});

async function main() {
    await client.connect();

    try {
        await client.query("BEGIN");

        await client.query(`
            DROP TABLE IF EXISTS items;
            DROP TABLE IF EXISTS categories;
        `);

        await client.query(`
            CREATE TABLE categories (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                description TEXT NOT NULL
            );
        `);

        await client.query(`
            CREATE TABLE items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                description TEXT NOT NULL,
                price NUMERIC(10, 2) NOT NULL,
                quantity INTEGER NOT NULL,
                category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE RESTRICT
            );
        `);

        const electronicsResult = await client.query(
            `INSERT INTO categories (name, description) VALUES ($1, $2) RETURNING id`,
            ["Electronics", "Devices, accessories, and tech essentials."]
        );
        const officeResult = await client.query(
            `INSERT INTO categories (name, description) VALUES ($1, $2) RETURNING id`,
            ["Office Supplies", "Tools and materials for a productive workspace."]
        );
        const kitchenResult = await client.query(
            `INSERT INTO categories (name, description) VALUES ($1, $2) RETURNING id`,
            ["Kitchen", "Equipment and everyday cooking essentials."]
        );

        await client.query(
            `
            INSERT INTO items (name, description, price, quantity, category_id)
            VALUES
                ($1, $2, $3, $4, $5),
                ($6, $7, $8, $9, $10),
                ($11, $12, $13, $14, $15),
                ($16, $17, $18, $19, $20)
            `,
            [
                "Wireless Mouse",
                "Ergonomic mouse with adjustable DPI.",
                24.99,
                18,
                electronicsResult.rows[0].id,
                "Notebook",
                "Hardcover ruled notebook for notes and planning.",
                6.5,
                120,
                officeResult.rows[0].id,
                "Desk Lamp",
                "LED desk lamp with dimmable settings.",
                32.0,
                14,
                officeResult.rows[0].id,
                "Chef Knife",
                "Stainless steel chef knife for daily prep.",
                41.75,
                9,
                kitchenResult.rows[0].id,
            ]
        );

        await client.query("COMMIT");
        console.log("Database seeded successfully.");
    } catch (error) {
        await client.query("ROLLBACK");
        console.error("Failed to seed database:", error);
        process.exitCode = 1;
    } finally {
        await client.end();
    }
}

main();